# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9705298521e3436300e43eb906118164"
name = "RMPimp"
application_url = "https://inventory-planner-4rvw.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/bulk_operations/finish"
  topics = [ "bulk_operations/finish" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/inventory_levels/update"
  topics = [ "inventory_levels/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/create"
  topics = [ "orders/create" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/products/create"
  topics = [ "products/create" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/products/delete"
  topics = [ "products/delete" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/products/update"
  topics = [ "products/update" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_metaobject_definitions,write_metaobject_definitions,read_metaobjects,write_metaobjects,read_orders,write_inventory,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://inventory-planner-4rvw.onrender.com/auth/callback" ]
